project_id = "zqpjxtlfhxjtenhhzaax"

[functions.create-user]
verify_jwt = false

[functions.verify-admin-credentials]
verify_jwt = false

[functions.create-supplier-user]
verify_jwt = false

[functions.create-salesperson-user]
verify_jwt = false

[functions.sync-erp]
verify_jwt = false
 
 [functions.sync-erp-docs]
 verify_jwt = false

 [functions.dispatch-webhook]
 verify_jwt = false

 [functions.create-demo-user]
 verify_jwt = false