// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/listar-lotes.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.86.2";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
function naoAutenticado() {
  return {
    content: [
      { type: "text", text: "N\xE3o autenticado. Conecte-se novamente." }
    ],
    isError: true
  };
}
function erro(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}
function ok(text, structuredContent) {
  return { content: [{ type: "text", text }], structuredContent };
}
function calcularITH(tempC, umidadePct) {
  return Number(
    (0.8 * tempC + umidadePct / 100 * (tempC - 14.4) + 46.4).toFixed(1)
  );
}
function idadeDias(dataAlojamento) {
  if (!dataAlojamento) return null;
  const ms = Date.now() - new Date(dataAlojamento).getTime();
  return Math.max(0, Math.floor(ms / 864e5));
}

// src/lib/mcp/tools/listar-lotes.ts
var listar_lotes_default = defineTool({
  name: "listar_lotes",
  title: "Listar lotes",
  description: "Lista os lotes da organiza\xE7\xE3o do usu\xE1rio (aves de corte e postura) com galp\xE3o, n\xFAcleo, idade em dias, quantidade alojada e status.",
  inputSchema: {
    status: z.enum(["ativo", "encerrado", "todos"]).optional().describe("Filtro de status. Padr\xE3o: ativo."),
    limite: z.number().int().optional().describe("M\xE1ximo de lotes retornados (padr\xE3o 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limite }, ctx) => {
    if (!ctx.isAuthenticated()) return naoAutenticado();
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("lotes").select(
      "id, status, quantidade_aves, data_alojamento, data_prevista_saida, linhagem, sexo, galpoes(nome), nucleos(nome, cidade, estado)"
    ).order("data_alojamento", { ascending: false }).limit(Math.min(Math.max(limite ?? 25, 1), 100));
    const filtro = status ?? "ativo";
    if (filtro === "ativo") query = query.eq("status", "ativo");
    else if (filtro === "encerrado") query = query.neq("status", "ativo");
    const { data, error } = await query;
    if (error) return erro(error.message);
    const lotes = (data ?? []).map((l) => ({
      id: l.id,
      status: l.status,
      galpao: l.galpoes?.nome ?? null,
      nucleo: l.nucleos?.nome ?? null,
      cidade: l.nucleos ? `${l.nucleos.cidade}/${l.nucleos.estado}` : null,
      aves_alojadas: l.quantidade_aves,
      idade_dias: idadeDias(l.data_alojamento),
      linhagem: l.linhagem,
      sexo: l.sexo,
      data_alojamento: l.data_alojamento,
      data_prevista_saida: l.data_prevista_saida
    }));
    if (lotes.length === 0) return ok("Nenhum lote encontrado com esse filtro.", { lotes });
    const linhas = lotes.map(
      (l) => `\u2022 ${l.galpao ?? "?"} (${l.nucleo ?? "?"}) \u2014 ${l.aves_alojadas} aves, ${l.idade_dias ?? "?"} dias, ${l.status} [id: ${l.id}]`
    );
    return ok(linhas.join("\n"), { lotes });
  }
});

// src/lib/mcp/tools/resumo-lote.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
var resumo_lote_default = defineTool2({
  name: "resumo_lote",
  title: "Resumo zoot\xE9cnico do lote",
  description: "Retorna o resumo de um lote: aves vivas, mortalidade acumulada (%), \xFAltima pesagem (peso m\xE9dio e convers\xE3o alimentar) e n\xEDvel de silo mais recente.",
  inputSchema: {
    lote_id: z2.string().describe("UUID do lote (obtido em listar_lotes).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ lote_id }, ctx) => {
    if (!ctx.isAuthenticated()) return naoAutenticado();
    const supabase = supabaseForUser(ctx);
    const { data: lote, error: eLote } = await supabase.from("lotes").select(
      "id, status, quantidade_aves, data_alojamento, linhagem, sexo, galpoes(nome), nucleos(nome)"
    ).eq("id", lote_id).maybeSingle();
    if (eLote) return erro(eLote.message);
    if (!lote) return erro("Lote n\xE3o encontrado ou sem permiss\xE3o de acesso.");
    const { data: registros, error: eMort } = await supabase.from("mortalidade").select("id, data_registro, mortalidade_itens(quantidade, motivo, peso_kg)").eq("lote_id", lote_id);
    if (eMort) return erro(eMort.message);
    let mortasTotal = 0;
    const porMotivo = {};
    for (const r of registros ?? []) {
      for (const it of r.mortalidade_itens ?? []) {
        mortasTotal += it.quantidade ?? 0;
        porMotivo[it.motivo] = (porMotivo[it.motivo] ?? 0) + (it.quantidade ?? 0);
      }
    }
    const { data: pesagens } = await supabase.from("pesagens").select("data_pesagem, conversao_alimentar, consumo_real_kg, nivel_silo_kg").eq("lote_id", lote_id).order("data_pesagem", { ascending: false }).limit(1);
    const ultimaPesagem = (pesagens ?? [])[0] ?? null;
    const alojadas = lote.quantidade_aves ?? 0;
    const vivas = Math.max(0, alojadas - mortasTotal);
    const mortalidadePct = alojadas > 0 ? Number((mortasTotal / alojadas * 100).toFixed(2)) : 0;
    const resumo = {
      lote_id,
      galpao: lote.galpoes?.nome ?? null,
      nucleo: lote.nucleos?.nome ?? null,
      status: lote.status,
      idade_dias: idadeDias(lote.data_alojamento),
      aves_alojadas: alojadas,
      aves_vivas: vivas,
      mortalidade_acumulada: mortasTotal,
      mortalidade_pct: mortalidadePct,
      mortalidade_por_motivo: porMotivo,
      ultima_pesagem: ultimaPesagem
    };
    const texto = [
      `Lote ${resumo.galpao ?? "?"} (${resumo.nucleo ?? "?"}) \u2014 ${resumo.status}`,
      `Idade: ${resumo.idade_dias ?? "?"} dias`,
      `Aves: ${vivas} vivas de ${alojadas} alojadas (mortalidade ${mortalidadePct}%)`,
      ultimaPesagem ? `\xDAltima pesagem ${ultimaPesagem.data_pesagem}: CA ${ultimaPesagem.conversao_alimentar ?? "-"}, consumo ${ultimaPesagem.consumo_real_kg ?? "-"} kg, silo ${ultimaPesagem.nivel_silo_kg ?? "-"} kg` : "Sem pesagens registradas."
    ].join("\n");
    return ok(texto, { resumo });
  }
});

// src/lib/mcp/tools/ambiencia-lote.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
var ambiencia_lote_default = defineTool3({
  name: "ambiencia_lote",
  title: "Ambi\xEAncia do lote",
  description: "Leituras mais recentes de temperatura, umidade e ITH dos sensores IoT do galp\xE3o do lote, com estado de cada dispositivo (online/offline).",
  inputSchema: {
    lote_id: z3.string().describe("UUID do lote (obtido em listar_lotes).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ lote_id }, ctx) => {
    if (!ctx.isAuthenticated()) return naoAutenticado();
    const supabase = supabaseForUser(ctx);
    const { data: lote, error: eLote } = await supabase.from("lotes").select("id, galpao_id, galpoes(nome)").eq("id", lote_id).maybeSingle();
    if (eLote) return erro(eLote.message);
    if (!lote) return erro("Lote n\xE3o encontrado ou sem permiss\xE3o de acesso.");
    const { data: dispositivos, error: eDisp } = await supabase.from("dispositivos_iot").select("id, nome, driver, ativo, ultimo_sync").eq("galpao_id", lote.galpao_id);
    if (eDisp) return erro(eDisp.message);
    const ids = (dispositivos ?? []).map((d) => d.id);
    if (ids.length === 0)
      return ok("Nenhum dispositivo IoT vinculado ao galp\xE3o deste lote.", { dispositivos: [] });
    const { data: leituras, error: eLeit } = await supabase.from("leituras_sensores").select("dispositivo_id, lido_em, temperatura_c, umidade_pct, co2_ppm, nh3_ppm, lux").in("dispositivo_id", ids).order("lido_em", { ascending: false }).limit(200);
    if (eLeit) return erro(eLeit.message);
    const ultimaPorDispositivo = /* @__PURE__ */ new Map();
    for (const l of leituras ?? []) {
      if (!ultimaPorDispositivo.has(l.dispositivo_id)) {
        ultimaPorDispositivo.set(l.dispositivo_id, l);
      }
    }
    const agora = Date.now();
    const itens = (dispositivos ?? []).map((d) => {
      const l = ultimaPorDispositivo.get(d.id);
      const syncMs = d.ultimo_sync ? new Date(d.ultimo_sync).getTime() : 0;
      const online = !!d.ativo && syncMs > 0 && agora - syncMs < 10 * 6e4;
      const temp = l?.temperatura_c ?? null;
      const ur = l?.umidade_pct ?? null;
      return {
        dispositivo: d.nome,
        driver: d.driver,
        online,
        lido_em: l?.lido_em ?? null,
        temperatura_c: temp,
        umidade_pct: ur,
        ith: temp != null && ur != null ? calcularITH(temp, ur) : null,
        co2_ppm: l?.co2_ppm ?? null,
        nh3_ppm: l?.nh3_ppm ?? null,
        lux: l?.lux ?? null
      };
    });
    const texto = [
      `Galp\xE3o ${lote.galpoes?.nome ?? "?"} \u2014 ${itens.length} dispositivo(s)`,
      ...itens.map(
        (i) => `\u2022 ${i.dispositivo} [${i.online ? "ONLINE" : "OFFLINE"}] ${i.temperatura_c ?? "-"}\xB0C \xB7 ${i.umidade_pct ?? "-"}% UR \xB7 ITH ${i.ith ?? "-"} (${i.lido_em ?? "sem leitura"})`
      )
    ].join("\n");
    return ok(texto, { galpao: lote.galpoes?.nome ?? null, dispositivos: itens });
  }
});

// src/lib/mcp/tools/decisoes-brain.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^3.25.76";
var decisoes_brain_default = defineTool4({
  name: "decisoes_brain",
  title: "Decis\xF5es recentes do Climate Brain",
  description: "Lista as decis\xF5es e comandos recentes do Climate Brain (ventila\xE7\xE3o, aquecimento, cortina, nebuliza\xE7\xE3o, ilumina\xE7\xE3o) com status de execu\xE7\xE3o.",
  inputSchema: {
    limite: z4.number().int().optional().describe("M\xE1ximo de comandos retornados (padr\xE3o 20)."),
    status: z4.enum(["sugerido", "aprovado", "enviado", "confirmado", "falhou", "todos"]).optional().describe("Filtro por status do comando. Padr\xE3o: todos.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limite, status }, ctx) => {
    if (!ctx.isAuthenticated()) return naoAutenticado();
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("comando_brain").select("id, funcao, estado_desejado, status, motivo, erro, created_at, enviado_em, galpao_id").order("created_at", { ascending: false }).limit(Math.min(Math.max(limite ?? 20, 1), 100));
    if (status && status !== "todos") query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return erro(error.message);
    const comandos = data ?? [];
    if (comandos.length === 0) return ok("Nenhum comando do Brain encontrado.", { comandos });
    const texto = comandos.map(
      (c) => `\u2022 ${new Date(c.created_at).toLocaleString("pt-BR")} \u2014 ${c.funcao} \u2192 ${JSON.stringify(c.estado_desejado)} [${c.status}]${c.motivo ? ` \xB7 ${c.motivo}` : ""}${c.erro ? ` \xB7 erro: ${c.erro}` : ""}`
    ).join("\n");
    return ok(texto, { comandos });
  }
});

// src/lib/mcp/tools/registrar-mortalidade.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z5 } from "npm:zod@^3.25.76";
var registrar_mortalidade_default = defineTool5({
  name: "registrar_mortalidade",
  title: "Registrar mortalidade",
  description: "Registra a mortalidade do dia de um lote, com quantidade por motivo e peso m\xE9dio opcional das aves (kg). Cria ou reutiliza o registro da data informada.",
  inputSchema: {
    lote_id: z5.string().describe("UUID do lote."),
    data: z5.string().optional().describe("Data do registro no formato AAAA-MM-DD. Padr\xE3o: hoje."),
    itens: z5.array(
      z5.object({
        motivo: z5.string().describe(
          "Motivo da baixa conforme cadastro do sistema (ex.: morte_natural, eliminacao, refugo)."
        ),
        quantidade: z5.number().int().describe("Quantidade de aves (inteiro positivo)."),
        peso_kg: z5.number().optional().describe("Peso m\xE9dio em KG das aves desse motivo (opcional, melhora a an\xE1lise).")
      })
    ).describe("Itens de mortalidade. Informe ao menos um.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false },
  handler: async ({ lote_id, data, itens }, ctx) => {
    if (!ctx.isAuthenticated()) return naoAutenticado();
    if (!itens?.length) return erro("Informe ao menos um item de mortalidade.");
    if (itens.some((i) => !Number.isInteger(i.quantidade) || i.quantidade <= 0))
      return erro("Cada item precisa de quantidade inteira maior que zero.");
    const supabase = supabaseForUser(ctx);
    const dataRegistro = data ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const { data: lote, error: eLote } = await supabase.from("lotes").select("id, integrado_id, status").eq("id", lote_id).maybeSingle();
    if (eLote) return erro(eLote.message);
    if (!lote) return erro("Lote n\xE3o encontrado ou sem permiss\xE3o de acesso.");
    if (lote.status !== "ativo") return erro("O lote n\xE3o est\xE1 ativo.");
    let registroId = null;
    const { data: existente } = await supabase.from("mortalidade").select("id").eq("lote_id", lote_id).eq("data_registro", dataRegistro).maybeSingle();
    if (existente) {
      registroId = existente.id;
    } else {
      const { data: criado, error: eIns } = await supabase.from("mortalidade").insert({
        lote_id,
        integrado_id: lote.integrado_id,
        data_registro: dataRegistro
      }).select("id").maybeSingle();
      if (eIns) return erro(eIns.message);
      registroId = criado?.id ?? null;
    }
    if (!registroId) return erro("N\xE3o foi poss\xEDvel criar o registro de mortalidade.");
    const { error: eItens } = await supabase.from("mortalidade_itens").insert(
      itens.map((i) => ({
        mortalidade_id: registroId,
        motivo: i.motivo,
        quantidade: i.quantidade,
        peso_kg: i.peso_kg ?? null
      }))
    );
    if (eItens) return erro(eItens.message);
    const total = itens.reduce((s, i) => s + i.quantidade, 0);
    return ok(`Mortalidade registrada em ${dataRegistro}: ${total} ave(s).`, {
      mortalidade_id: registroId,
      data_registro: dataRegistro,
      total
    });
  }
});

// src/lib/mcp/index.ts
var projectRef = "zqpjxtlfhxjtenhhzaax";
var mcp_default = defineMcp({
  name: "gsa-tibiri-mcp",
  title: "GSA Tibiri \u2014 Gest\xE3o Av\xEDcola",
  version: "0.1.0",
  instructions: "Ferramentas do GSA Tibiri, sistema de gest\xE3o av\xEDcola. Use `listar_lotes` para descobrir os lotes e obter os IDs, `resumo_lote` para indicadores zoot\xE9cnicos (aves vivas, mortalidade, convers\xE3o alimentar), `ambiencia_lote` para temperatura/umidade/ITH dos sensores IoT, `decisoes_brain` para auditar as decis\xF5es do Climate Brain e `registrar_mortalidade` para lan\xE7ar baixas do dia. Pesos sempre em KG.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [listar_lotes_default, resumo_lote_default, ambiencia_lote_default, decisoes_brain_default, registrar_mortalidade_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
